### ISSUE TITLE
ResolveIPtoHost assumes fixed location of CN in cert subject

### ISSUE THREAD

**Issue by wwtorrey** [HewlettPackard/HPEStoragePowerShellToolkit#7]
In the function ResolvePtoHost the CN location is assumed to be in a fixed location in the certificate subject.
Suggest change to locate CN in subject and grab value.

$global:cert_hostname = ($CertSubject.Split(',').trim() | Where-Object {$_ -like 'CN=*'}).SubString(3)

File: MSA.scripts\helpers.ps1:629

**Comment by chris-lionetti** [comment]
This is an excellent modification. I have solved this in two ways..the master module now contains an 'Import-HPESANCertificate' command which will import the certificate for you, or via your fix the embedded ResolveIPToHost is also now working.

**Comment by chris-lionetti** [comment]
Thank you for your contribution

**Comment by wwtorrey** [comment]
The issue is that the cert_hostname is not resolved from the subject string correctly.
In the function ResolveIPtoHost the CN location is still assumed to be in a **fixed** location in the certificate subject.

For example,
Given the subject of "E=bill.torrey@hpe.com, CN=MSA2070-FC1-A, OU=MSA, O=HPE, L=FTC, S=CO, C=US"

In helpers.ps1:418
$global:cert_hostname = ($CertSubject.Substring(($CertSubject.IndexOf("=")+1),($CertSubject.IndexOf(",")-3))).trim()

PS C:\> $CertSubject = "E=bill.torrey@hpe.com, CN=MSA2070-FC1-A, OU=MSA, O=HPE, L=FTC, S=CO, C=US"
PS C:\> ($CertSubject.Substring(($CertSubject.IndexOf("=")+1),($CertSubject.IndexOf(",")-3))).trim()
bill.torrey@hpe.co

Here is a reworked function that appears to be working, however, the new Group name does not appear to be picked up for the base URL. However, that does not appear to be an issue. Also, I did not test fail DNS lookups.

function ResolveIPtoHost
{
param(  [Parameter(Mandatory)]      [string]$CertSubject, 
        [Parameter(Mandatory)]      [string]$Group
        )

    # we will check if the host name given as input matches the host name in the certificate.
    # if IP is given as input and the certificate has hostname (FQDN) then we will use the hostname name but 
    # before that we will ensurelookup from hostname to IP works.            
    # $global:cert_hostname = ($CertSubject.Substring(($CertSubject.IndexOf("=")+1),($CertSubject.IndexOf(",")-3))).trim()
    # Get the common name from the certificate subject. The common name is the hostname (or ip) of the server.
    $cn = ($CertSubject.Split(',').trim() | Where-Object {$_ -like 'CN=*'})
    if($cn)
    {
        $global:cert_hostname = $cn.SubString(3)
    } else {
        Write-Error "Unable to extract the common name from the certificate subject. Please verify the certificate details shown below and use ImportServerCertificate command line parameter to proceed. `n $CertSubject `n`n" -ErrorAction Stop
    }

    # check if the input and cert hostname matches, if yes we are good to go
    # Else the input must have ben the IP address, we will if cert hostname can be resolved to match the input hostname (IP).
    if ($Group -ne $cert_hostname)
    {
        # we will look up the DNS to resolve the cert_hostname. 
        # Use the cert hostname for lookup, if it is not available then use the input hostname(IP).
        $lookup_hostname = $cert_hostname
        if (!$cert_hostname){
            $lookup_hostname = $Group
        }
        
        try
        {
            # Resolve the cert hostname to IP address and compare it with the input hostname(IP). If they match then we are good to go.
            $resolved_ip = [System.Net.DNS]::GetHostEntry($lookup_hostname).AddressList 
            $resolved_ip = $resolved_ip | Select-Object -ExpandProperty IPAddressToString
            $group_ip = [System.Net.DNS]::GetHostEntry($Group).AddressList
            $group_ip = $group_ip | Select-Object  -ExpandProperty IPAddressToString

            # will come here if the host got resolved.
            
            Write-Verbose " $lookup_hostname is host-name for provided input $Group IP address"
            
            if ($resolved_ip -ne $group_ip)             
            {
                # most probably this will not happen, just to be defensive adding this code.
                # this is the same host as the certificate hostname got resolved to the input hostname(IP)
                # we  will start using the cert hostname for all the calls from this point in this session.
                
                Write-Error "Unable to resolve the certificate hostname to match the provided input hostname/IP. `n`n $_.Exception.Message"  -ErrorAction Stop
            }
            else
            {
                # we are good to go.
                Write-Verbose " Resolved name and input name matches: $Group IP address"
                $global:Group = $cert_hostname
            }
        }
        catch 
        {   # unable to resolve the cert hostname. Host not reachable. Error out!.
            Write-Error "Unable to resolve the certificate hostname. Host not reachable. `n`n $_.Exception.Message"  -ErrorAction Stop
        }
    }
    else
    {   # we are good to go.    
        Write-Verbose "Host-name given as input matches with certificate name"
    }
}
